//🫖ketl
#ifndef ketl_compiler_token_h
#define ketl_compiler_token_h

#include "ketl/utils.h"

typedef uint8_t ketl_token_type;

enum {
    KETL_TOKEN_TYPE_ID,
    KETL_TOKEN_TYPE_LITERAL_NULL,
    KETL_TOKEN_TYPE_LITERAL_FALSE,
    KETL_TOKEN_TYPE_LITERAL_TRUE,
    KETL_TOKEN_TYPE_LITERAL_INTEGER,
    KETL_TOKEN_TYPE_LITERAL_STRING,
    KETL_TOKEN_TYPE_LITERAL_CHAR,
    KETL_TOKEN_TYPE_PARENTHESIS_LEFT,
    KETL_TOKEN_TYPE_PARENTHESIS_RIGHT,
    KETL_TOKEN_TYPE_CURLY_LEFT,
    KETL_TOKEN_TYPE_CURLY_RIGHT,
    KETL_TOKEN_TYPE_SQUARE_LEFT,
    KETL_TOKEN_TYPE_SQUARE_RIGHT,
    KETL_TOKEN_TYPE_DOT,
    KETL_TOKEN_TYPE_COMMA,
    KETL_TOKEN_TYPE_QUESTION_MARK,
    KETL_TOKEN_TYPE_DOLLAR,
    KETL_TOKEN_TYPE_COLON,
    KETL_TOKEN_TYPE_ARROW_RIGHT,
    KETL_TOKEN_TYPE_TERMINATION_CHARACTER,
    KETL_TOKEN_TYPE_LOGICAL_NOT,
    KETL_TOKEN_TYPE_LOGICAL_AND,
    KETL_TOKEN_TYPE_LOGICAL_OR,
    KETL_TOKEN_TYPE_LESS,
    KETL_TOKEN_TYPE_LESS_OR_EQUAL,
    KETL_TOKEN_TYPE_GREATER,
    KETL_TOKEN_TYPE_GREATER_OR_EQUAL,
    KETL_TOKEN_TYPE_EQUAL,
    KETL_TOKEN_TYPE_NOT_EQUAL,
    KETL_TOKEN_TYPE_BITWISE_NOT,
    KETL_TOKEN_TYPE_BITWISE_AND,
    KETL_TOKEN_TYPE_BITWISE_OR,
    KETL_TOKEN_TYPE_BITWISE_XOR,
    KETL_TOKEN_TYPE_BITWISE_SHIFT_LEFT,
    KETL_TOKEN_TYPE_BITWISE_SHIFT_RIGHT,
    KETL_TOKEN_TYPE_INCREMENT,
    KETL_TOKEN_TYPE_DECREMENT,
    KETL_TOKEN_TYPE_PLUS,
    KETL_TOKEN_TYPE_MINUS,
    KETL_TOKEN_TYPE_MULTIPLY,
    KETL_TOKEN_TYPE_DIVIDE,
    KETL_TOKEN_TYPE_REMAINDER,
    KETL_TOKEN_TYPE_CONCAT,
    KETL_TOKEN_TYPE_ASSIGN,
    KETL_TOKEN_TYPE_ASSIGN_PLUS,
    KETL_TOKEN_TYPE_ASSIGN_MINUS,
    KETL_TOKEN_TYPE_ASSIGN_MULTIPLY,
    KETL_TOKEN_TYPE_ASSIGN_DIVIDE,
    KETL_TOKEN_TYPE_ASSIGN_REMAINDER,
    KETL_TOKEN_TYPE_ASSIGN_CONCAT,
    KETL_TOKEN_TYPE_ASSIGN_BITWISE_SHIFT_LEFT,
    KETL_TOKEN_TYPE_ASSIGN_BITWISE_SHIFT_RIGHT,
    KETL_TOKEN_TYPE_ASSIGN_BITWISE_AND,
    KETL_TOKEN_TYPE_ASSIGN_BITWISE_OR,
    KETL_TOKEN_TYPE_ASSIGN_BITWISE_XOR,
    KETL_TOKEN_TYPE_I8,
    KETL_TOKEN_TYPE_I16,
    KETL_TOKEN_TYPE_I32,
    KETL_TOKEN_TYPE_I64,
    KETL_TOKEN_TYPE_U8,
    KETL_TOKEN_TYPE_U16,
    KETL_TOKEN_TYPE_U32,
    KETL_TOKEN_TYPE_U64,
    KETL_TOKEN_TYPE_F32,
    KETL_TOKEN_TYPE_F64,
    KETL_TOKEN_TYPE_BOOL,
    KETL_TOKEN_TYPE_BREAK,
    KETL_TOKEN_TYPE_CASE,
    KETL_TOKEN_TYPE_CHAR,
    KETL_TOKEN_TYPE_CIMPORT,
    KETL_TOKEN_TYPE_CLASS,
    KETL_TOKEN_TYPE_CONST,
    KETL_TOKEN_TYPE_CONTINUE,
    KETL_TOKEN_TYPE_DEFAULT,
    KETL_TOKEN_TYPE_DO,
    KETL_TOKEN_TYPE_ELSE,
    KETL_TOKEN_TYPE_ENUM,
    KETL_TOKEN_TYPE_EXPORT,
    KETL_TOKEN_TYPE_FN,
    KETL_TOKEN_TYPE_FOR,
    KETL_TOKEN_TYPE_IF,
    KETL_TOKEN_TYPE_IMPORT,
    KETL_TOKEN_TYPE_MIMIC,
    KETL_TOKEN_TYPE_NONE,
    KETL_TOKEN_TYPE_RAW,
    KETL_TOKEN_TYPE_RETURN,
    KETL_TOKEN_TYPE_STRUCT,
    KETL_TOKEN_TYPE_SWITCH,
    KETL_TOKEN_TYPE_UNION,
    KETL_TOKEN_TYPE_VAR,
    KETL_TOKEN_TYPE_WHILE,
    KETL_TOKEN_TYPE_EOF,
    KETL_TOKEN_TYPE_ERROR,
};

typedef uint16_t ketl_token_length_t;
typedef uint32_t ketl_token_offset_t;

ANN_DEFINE(ketl_token_t) {
    ketl_token_type type;
    ketl_token_length_t length;
    ketl_token_offset_t offset;
};

typedef uint32_t ketl_token_iterator_t;

#endif // ketl_compiler_token_h
