//🫖ketl
#ifndef ketl_bytecode_h
#define ketl_bytecode_h

#include "ketl/utils.h"

typedef uint8_t ketl_bytecode_instr;

enum __KETL_BYTECODE_INSTRUCTION {
    KETL_BYTECODE_NONE,
    KETL_BYTECODE_STACK_PROLOG,

    KETL_BYTECODE_8PUSH_ARG,
    KETL_BYTECODE_16PUSH_ARG,
    KETL_BYTECODE_32PUSH_ARG,
    KETL_BYTECODE_64PUSH_ARG,
    KETL_BYTECODE_CALL,

    KETL_BYTECODE_RETURN,
    KETL_BYTECODE_8RETURN,
    KETL_BYTECODE_16RETURN,
    KETL_BYTECODE_32RETURN,
    KETL_BYTECODE_64RETURN,

    KETL_BYTECODE_8ASSIGN,
    KETL_BYTECODE_16ASSIGN,
    KETL_BYTECODE_32ASSIGN,
    KETL_BYTECODE_64ASSIGN,

    KETL_BYTECODE_8LOAD_CONST,
    KETL_BYTECODE_16LOAD_CONST,
    KETL_BYTECODE_32LOAD_CONST,
    KETL_BYTECODE_64LOAD_CONST,

    KETL_BYTECODE_8UADD,
    KETL_BYTECODE_16UADD,
    KETL_BYTECODE_32UADD,
    KETL_BYTECODE_64UADD,
    KETL_BYTECODE_8IADD,
    KETL_BYTECODE_16IADD,
    KETL_BYTECODE_32IADD,
    KETL_BYTECODE_64IADD,

    KETL_BYTECODE_8USUB,
    KETL_BYTECODE_16USUB,
    KETL_BYTECODE_32USUB,
    KETL_BYTECODE_64USUB,
    KETL_BYTECODE_8ISUB,
    KETL_BYTECODE_16ISUB,
    KETL_BYTECODE_32ISUB,
    KETL_BYTECODE_64ISUB,

    KETL_BYTECODE_8UMULTIPLY,
    KETL_BYTECODE_16UMULTIPLY,
    KETL_BYTECODE_32UMULTIPLY,
    KETL_BYTECODE_64UMULTIPLY,
    KETL_BYTECODE_8IMULTIPLY,
    KETL_BYTECODE_16IMULTIPLY,
    KETL_BYTECODE_32IMULTIPLY,
    KETL_BYTECODE_64IMULTIPLY,

    KETL_BYTECODE_8UDIVIDE,
    KETL_BYTECODE_16UDIVIDE,
    KETL_BYTECODE_32UDIVIDE,
    KETL_BYTECODE_64UDIVIDE,
    KETL_BYTECODE_8IDIVIDE,
    KETL_BYTECODE_16IDIVIDE,
    KETL_BYTECODE_32IDIVIDE,
    KETL_BYTECODE_64IDIVIDE,

    KETL_BYTECODE_8UMODULO,
    KETL_BYTECODE_16UMODULO,
    KETL_BYTECODE_32UMODULO,
    KETL_BYTECODE_64UMODULO,
    KETL_BYTECODE_8IMODULO,
    KETL_BYTECODE_16IMODULO,
    KETL_BYTECODE_32IMODULO,
    KETL_BYTECODE_64IMODULO,

    KETL_BYTECODE_8UEQUAL,
    KETL_BYTECODE_16UEQUAL,
    KETL_BYTECODE_32UEQUAL,
    KETL_BYTECODE_64UEQUAL,
    KETL_BYTECODE_8IEQUAL,
    KETL_BYTECODE_16IEQUAL,
    KETL_BYTECODE_32IEQUAL,
    KETL_BYTECODE_64IEQUAL,

    KETL_BYTECODE_8UNOT_EQUAL,
    KETL_BYTECODE_16UNOT_EQUAL,
    KETL_BYTECODE_32UNOT_EQUAL,
    KETL_BYTECODE_64UNOT_EQUAL,
    KETL_BYTECODE_8INOT_EQUAL,
    KETL_BYTECODE_16INOT_EQUAL,
    KETL_BYTECODE_32INOT_EQUAL,
    KETL_BYTECODE_64INOT_EQUAL,

    KETL_BYTECODE_8ULESS,
    KETL_BYTECODE_16ULESS,
    KETL_BYTECODE_32ULESS,
    KETL_BYTECODE_64ULESS,
    KETL_BYTECODE_8ILESS,
    KETL_BYTECODE_16ILESS,
    KETL_BYTECODE_32ILESS,
    KETL_BYTECODE_64ILESS,

    KETL_BYTECODE_8ULESS_OR_EQUAL,
    KETL_BYTECODE_16ULESS_OR_EQUAL,
    KETL_BYTECODE_32ULESS_OR_EQUAL,
    KETL_BYTECODE_64ULESS_OR_EQUAL,
    KETL_BYTECODE_8ILESS_OR_EQUAL,
    KETL_BYTECODE_16ILESS_OR_EQUAL,
    KETL_BYTECODE_32ILESS_OR_EQUAL,
    KETL_BYTECODE_64ILESS_OR_EQUAL,

    KETL_BYTECODE_8UGREATER,
    KETL_BYTECODE_16UGREATER,
    KETL_BYTECODE_32UGREATER,
    KETL_BYTECODE_64UGREATER,
    KETL_BYTECODE_8IGREATER,
    KETL_BYTECODE_16IGREATER,
    KETL_BYTECODE_32IGREATER,
    KETL_BYTECODE_64IGREATER,

    KETL_BYTECODE_8UGREATER_OR_EQUAL,
    KETL_BYTECODE_16UGREATER_OR_EQUAL,
    KETL_BYTECODE_32UGREATER_OR_EQUAL,
    KETL_BYTECODE_64UGREATER_OR_EQUAL,
    KETL_BYTECODE_8IGREATER_OR_EQUAL,
    KETL_BYTECODE_16IGREATER_OR_EQUAL,
    KETL_BYTECODE_32IGREATER_OR_EQUAL,
    KETL_BYTECODE_64IGREATER_OR_EQUAL,
};

typedef uint16_t ketl_bytecode_stack_offset;

KETL_DEFINE(ketl_bytecode) {
    uint8_t* pInstructions;
    uint8_t* pLabels;
    uint32_t instructionsCount;
};

uint8_t ketl_bytecode_decode_instruction_length(ketl_bytecode_instr instruction);

uint32_t ketl_bytecode_format(uint8_t* pInstruction, uint8_t* pLabels, char* buffer, uint32_t bufferSize);

#endif // ketl_bytecode_h
