//🫖ketl
#ifndef ketl_bytecode_h
#define ketl_bytecode_h

#include "ketl/utils.h"

typedef uint8_t ketl_bytecode_instr;

enum __KETL_BYTECODE_INSTRUCTION {
    KETL_BYTECODE_NONE,
    KETL_BYTECODE_STACK_PROLOG,

    KETL_BYTECODE_8PUSH_ARG,
    KETL_BYTECODE_16PUSH_ARG,
    KETL_BYTECODE_32PUSH_ARG,
    KETL_BYTECODE_64PUSH_ARG,
    KETL_BYTECODE_CALL,

    KETL_BYTECODE_RETURN,
    KETL_BYTECODE_8RETURN,
    KETL_BYTECODE_16RETURN,
    KETL_BYTECODE_32RETURN,
    KETL_BYTECODE_64RETURN,

    KETL_BYTECODE_8LOAD_GLOBAL,
    KETL_BYTECODE_16LOAD_GLOBAL,
    KETL_BYTECODE_32LOAD_GLOBAL,
    KETL_BYTECODE_64LOAD_GLOBAL,

    KETL_BYTECODE_8LOAD_UCONST,
    KETL_BYTECODE_16LOAD_UCONST,
    KETL_BYTECODE_32LOAD_UCONST,
    KETL_BYTECODE_64LOAD_UCONST,
    KETL_BYTECODE_8LOAD_ICONST,
    KETL_BYTECODE_16LOAD_ICONST,
    KETL_BYTECODE_32LOAD_ICONST,
    KETL_BYTECODE_64LOAD_ICONST,

    KETL_BYTECODE_8UADD,
    KETL_BYTECODE_16UADD,
    KETL_BYTECODE_32UADD,
    KETL_BYTECODE_64UADD,
    KETL_BYTECODE_8IADD,
    KETL_BYTECODE_16IADD,
    KETL_BYTECODE_32IADD,
    KETL_BYTECODE_64IADD,

    KETL_BYTECODE_8UMULTIPLY,
    KETL_BYTECODE_16UMULTIPLY,
    KETL_BYTECODE_32UMULTIPLY,
    KETL_BYTECODE_64UMULTIPLY,
    KETL_BYTECODE_8IMULTIPLY,
    KETL_BYTECODE_16IMULTIPLY,
    KETL_BYTECODE_32IMULTIPLY,
    KETL_BYTECODE_64IMULTIPLY,
};

typedef uint16_t ketl_bytecode_stack_offset;

KETL_DEFINE(ketl_bytecode) {
    uint8_t* pInstructions;
    uint8_t* pLabels;
    uint32_t instructionsCount;
};

uint8_t ketl_bytecode_decode_instruction_length(ketl_bytecode_instr instruction);

uint32_t ketl_bytecode_format(uint8_t* pInstruction, uint8_t* pLabels, char* buffer, uint32_t bufferSize);

#endif // ketl_bytecode_h
